# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=300, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
