# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='source',
        ),
        migrations.AlterField(
            model_name='poster',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
